version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
      - npm install -g aws-cdk
  build:
    commands:
      - cdk synth

artifacts:
  files:
    - cdk.out/*
